spring:
  application:
    name: Spring-boot-demo-with-AWS-S3
#  config:
#    import: optional:aws-secretsmanager:s3_credential

#database:
#  name: ${S3_ACCESS_KEY}

server:
  port: 9092

aws:
  secret:
    key:
      id: "IM6ZZ4Ks9U51riWK+db1hA1vZLVCUwP9sH0TQXw6"
  access:
    key: "AKIAZ24ISRUKO4BPTVUF"